import React from 'react';
import { ArrowLeft, Shield, Mail } from 'lucide-react';

interface PrivacyPolicyPageProps {
  onBackToApp: () => void;
}

export const PrivacyPolicyPage: React.FC<PrivacyPolicyPageProps> = ({ onBackToApp }) => {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <button
              onClick={onBackToApp}
              className="flex items-center space-x-2 text-blue-600 hover:text-blue-700 font-medium transition-colors"
            >
              <ArrowLeft className="w-4 h-4" />
              <span>Back to App</span>
            </button>
            <div className="flex items-center space-x-2">
              <img 
                src="/logo.png" 
                alt="NexToImage Logo" 
                className="h-8 w-auto object-contain"
              />
              <h1 className="text-xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                NexToImage
              </h1>
            </div>
            <div className="w-20"></div> {/* Spacer for centering */}
          </div>
        </div>
      </header>

      {/* Content */}
      <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
          {/* Header Section */}
          <div className="bg-gradient-to-r from-blue-500 to-purple-600 px-8 py-12 text-white">
            <div className="flex items-center space-x-3 mb-4">
              <Shield className="w-8 h-8" />
              <h1 className="text-3xl font-bold">Privacy Policy</h1>
            </div>
            <p className="text-blue-100 text-lg">
              Your privacy and data protection are our top priorities
            </p>
          </div>

          {/* Content Section */}
          <div className="px-8 py-12">
            <div className="prose prose-gray max-w-none">
              <div className="mb-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-4">NextoImage Privacy Policy</h2>
                <p className="text-gray-600 mb-6">
                  <strong>Effective Date:</strong> October 1, 2025
                </p>
              </div>

              <div className="space-y-8">
                <section>
                  <h3 className="text-xl font-semibold text-gray-900 mb-4">1. Introduction</h3>
                  <p className="text-gray-700 leading-relaxed">
                    NextoImage ("we," "us," or "our") provides AI-based image and video generation and editing services. This Privacy Policy explains how we collect, use, and protect the personal information of our users ("you," "your") when you use our website and services.
                  </p>
                  <p className="text-gray-700 leading-relaxed mt-4">
                    By using NextoImage, you agree to the practices described in this Privacy Policy.
                  </p>
                </section>

                <section>
                  <h3 className="text-xl font-semibold text-gray-900 mb-4">2. Information We Collect</h3>
                  <p className="text-gray-700 leading-relaxed mb-4">
                    When you use NextoImage, we may collect the following information:
                  </p>
                  <ul className="list-disc list-inside space-y-2 text-gray-700 ml-4">
                    <li><strong>Account Information:</strong> name, email address, and password (stored securely in hashed form).</li>
                    <li><strong>Usage Data:</strong> IP address, device and browser information, and activity logs related to your use of the platform.</li>
                    <li><strong>Content Data:</strong> inputs you provide (such as prompts, text, images, or videos) and the outputs generated by the service.</li>
                    <li><strong>Payment Information:</strong> Payments are processed by iyzico, a third-party payment provider. We do not store or process credit or debit card numbers. We only store transaction references and billing details provided by iyzico.</li>
                    <li><strong>Cookies and Tracking:</strong> cookies and similar technologies to maintain sessions and improve site performance.</li>
                    <li><strong>Support Information:</strong> when you contact us, we collect your email address and the content of your communication.</li>
                  </ul>
                </section>

                <section>
                  <h3 className="text-xl font-semibold text-gray-900 mb-4">3. How We Use Your Information</h3>
                  <p className="text-gray-700 leading-relaxed mb-4">
                    We use your information solely to:
                  </p>
                  <ul className="list-disc list-inside space-y-2 text-gray-700 ml-4">
                    <li>Provide and maintain our services.</li>
                    <li>Process payments through iyzico.</li>
                    <li>Authenticate and manage user accounts.</li>
                    <li>Ensure the security and proper functioning of the platform.</li>
                    <li>Communicate with you regarding your account or service updates.</li>
                  </ul>
                  <p className="text-gray-700 leading-relaxed mt-4">
                    We do not use your data for marketing purposes without your explicit consent.
                  </p>
                </section>

                <section>
                  <h3 className="text-xl font-semibold text-gray-900 mb-4">4. Generated Content and Data Use</h3>
                  <ul className="list-disc list-inside space-y-2 text-gray-700 ml-4">
                    <li>The inputs (prompts, text, uploads) and outputs (generated images/videos) you create belong to you.</li>
                    <li>We do not use your content to train or improve AI models.</li>
                    <li>Content may be temporarily stored to deliver the service and to ensure stability and security, after which it is deleted.</li>
                  </ul>
                </section>

                <section>
                  <h3 className="text-xl font-semibold text-gray-900 mb-4">5. Data Sharing</h3>
                  <p className="text-gray-700 leading-relaxed mb-4">
                    We do not sell your personal information. We may share limited data only with:
                  </p>
                  <ul className="list-disc list-inside space-y-2 text-gray-700 ml-4">
                    <li><strong>Payment Provider (iyzico):</strong> to process transactions.</li>
                    <li><strong>Service Providers:</strong> such as hosting and cloud infrastructure providers that help operate the platform.</li>
                    <li><strong>Legal Authorities:</strong> if required to comply with law or enforce our Terms of Service.</li>
                  </ul>
                </section>

                <section>
                  <h3 className="text-xl font-semibold text-gray-900 mb-4">6. International Data Transfers</h3>
                  <p className="text-gray-700 leading-relaxed">
                    Our services may be hosted or processed in countries other than your own. By using our services, you consent to such transfers. We take steps to ensure your data is protected through secure practices and agreements with our providers.
                  </p>
                </section>

                <section>
                  <h3 className="text-xl font-semibold text-gray-900 mb-4">7. Data Retention</h3>
                  <ul className="list-disc list-inside space-y-2 text-gray-700 ml-4">
                    <li>We retain your account information as long as your account is active.</li>
                    <li>When you delete your account, we remove your personal data except where retention is required by law (e.g., financial transaction records).</li>
                    <li>Support communications may be kept for a reasonable period for record-keeping.</li>
                  </ul>
                </section>

                <section>
                  <h3 className="text-xl font-semibold text-gray-900 mb-4">8. Your Rights</h3>
                  <p className="text-gray-700 leading-relaxed mb-4">
                    Depending on your location, you may have rights under applicable laws (such as GDPR or CCPA), including:
                  </p>
                  <ul className="list-disc list-inside space-y-2 text-gray-700 ml-4">
                    <li>The right to access, update, or delete your personal data.</li>
                    <li>The right to request a copy of your data.</li>
                    <li>The right to restrict or object to processing.</li>
                    <li>The right to withdraw consent where processing is based on consent.</li>
                  </ul>
                  <p className="text-gray-700 leading-relaxed mt-4">
                    To exercise your rights, contact us at: <a href="mailto:doruknextoimage@gmail.com" className="text-blue-600 hover:text-blue-700 font-medium">doruknextoimage@gmail.com</a>
                  </p>
                </section>

                <section>
                  <h3 className="text-xl font-semibold text-gray-900 mb-4">9. Security</h3>
                  <p className="text-gray-700 leading-relaxed">
                    We use industry-standard measures to protect your personal data, including encryption in transit (HTTPS), secure password hashing, and access controls. However, no system is completely secure, and we cannot guarantee absolute protection.
                  </p>
                </section>

                <section>
                  <h3 className="text-xl font-semibold text-gray-900 mb-4">10. Children's Privacy</h3>
                  <p className="text-gray-700 leading-relaxed">
                    Our service is not directed to children under the age of 16. We do not knowingly collect personal information from children. If we become aware that a child under 16 has provided personal data, we will delete it immediately.
                  </p>
                </section>

                <section>
                  <h3 className="text-xl font-semibold text-gray-900 mb-4">11. Cookies</h3>
                  <p className="text-gray-700 leading-relaxed mb-4">
                    We use cookies and similar technologies to:
                  </p>
                  <ul className="list-disc list-inside space-y-2 text-gray-700 ml-4">
                    <li>Keep you logged in during a session.</li>
                    <li>Improve functionality and performance of the site.</li>
                  </ul>
                  <p className="text-gray-700 leading-relaxed mt-4">
                    You can manage or disable cookies through your browser settings.
                  </p>
                </section>

                <section>
                  <h3 className="text-xl font-semibold text-gray-900 mb-4">12. Changes to This Policy</h3>
                  <p className="text-gray-700 leading-relaxed">
                    We may update this Privacy Policy from time to time. If material changes occur, we will notify you by posting a notice on our website or by email. The "Effective Date" at the top will indicate when it was last revised.
                  </p>
                </section>

                <section>
                  <h3 className="text-xl font-semibold text-gray-900 mb-4">13. Contact Us</h3>
                  <p className="text-gray-700 leading-relaxed mb-4">
                    If you have any questions about this Privacy Policy or how we handle your data, please contact us at:
                  </p>
                  <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 flex items-center space-x-3">
                    <Mail className="w-5 h-5 text-blue-600" />
                    <a 
                      href="mailto:doruknextoimage@gmail.com" 
                      className="text-blue-600 hover:text-blue-700 font-medium text-lg"
                    >
                      doruknextoimage@gmail.com
                    </a>
                  </div>
                </section>
              </div>
            </div>
          </div>
        </div>

        {/* Back to Top Button */}
        <div className="text-center mt-8">
          <button
            onClick={onBackToApp}
            className="bg-gradient-to-r from-blue-500 to-purple-600 text-white px-8 py-3 rounded-lg font-medium hover:from-blue-600 hover:to-purple-700 transition-all duration-200 transform hover:scale-105"
          >
            Back to NexToImage
          </button>
        </div>
      </div>
    </div>
  );
};